# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_messagestore_have_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('is_parsed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='news_count',
            field=models.IntegerField(default=0),
        ),
    ]
